version: 2.1
orbs:
  node: circleci/node@5.1.0


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            cd server
            wget https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.10.0.tar.gz
            tar -xzvf apache-jena-fuseki-4.10.0.tar.gz
            fuseki-server
            npm install
            npm test --forceExit

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
