version: 2.1
orbs:
  node: circleci/node@5.1.0


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: stain/jena-fuseki
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            cd server
            echo "hello world"
            docker run -d -p 127.0.0.1:3030:3030 stain/jena-fuseki
            echo "hello world2"
            npm install
            npm test --forceExit

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
